# Config
title: Apéroweb Toulouse
description: "Le rendez-vous des gens qui font le web sur Toulouse"
url: http://toulouse.aperoweb.fr
baseurl: ""
repository: aperoweb-toulouse/aperoweb-toulouse.github.com

# SEO Tag
author: aperoweb_tlse
twitter:
  username: aperoweb_tlse
logo: /img/aperoweb.png

# Social metadata (JSON-LD)
social:
  name: Apéroweb Toulouse
  links:
    - https://twitter.com/aperoweb_tlse
    - https://github.com/aperoweb-toulouse

call_for_speaker:
  url: http://goo.gl/forms/U5gQ9znhmY

analytics:
  google:
    tracking_id: UA-69372239-1

sass:
  sass_dir: _sass
  style:    :compressed

exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package.json
  - Procfile
  - README.md
  - script
  - vendor

gems:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
